// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KapetolLoyaltyApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723114713_RenameB1B2Reward")]
    partial class RenameB1B2Reward
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QRCodeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Alec Cresencio",
                            Phone = "09279179977",
                            QRCodeId = "5c0ad0f3-da3f-4885-9037-b276bb68a7c1"
                        });
                });

            modelBuilder.Entity("PointsLedger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("PointsLedger");
                });

            modelBuilder.Entity("Reward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PointsCost")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rewards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "10% discount on any drinks",
                            IsActive = true,
                            Name = "10% Discount on Drinks",
                            PointsCost = 20
                        },
                        new
                        {
                            Id = 2,
                            Description = "Redeem for a free mediano hot or iced tea",
                            IsActive = true,
                            Name = "Free Mediano Hot/Iced Tea",
                            PointsCost = 30
                        },
                        new
                        {
                            Id = 3,
                            Description = "Redeem for a free mediano hot or iced americano",
                            IsActive = true,
                            Name = "Free Mediano Hot/Iced Americano",
                            PointsCost = 40
                        },
                        new
                        {
                            Id = 4,
                            Description = "20% discount on any drinks",
                            IsActive = true,
                            Name = "20% Discount on Drinks",
                            PointsCost = 60
                        },
                        new
                        {
                            Id = 5,
                            Description = "Redeem for a free waffle (B6)",
                            IsActive = true,
                            Name = "Free Waffle (B6)",
                            PointsCost = 80
                        },
                        new
                        {
                            Id = 6,
                            Description = "Redeem for a free Waffle Cheesy Egg (B8)",
                            IsActive = true,
                            Name = "Free Waffle Cheesy Egg (B8)",
                            PointsCost = 100
                        },
                        new
                        {
                            Id = 7,
                            Description = "Redeem for a free Spam, Egg, Rice (B12)",
                            IsActive = true,
                            Name = "Free Spam, Egg, Rice (B12)",
                            PointsCost = 120
                        },
                        new
                        {
                            Id = 8,
                            Description = "Redeem for a free any mediano frappe",
                            IsActive = true,
                            Name = "Free Mediano Frappe",
                            PointsCost = 140
                        },
                        new
                        {
                            Id = 9,
                            Description = "Redeem for a free Bacon, Egg, and Rice Meal (B1) or Sausage, Egg, and Rice Meal (B2)",
                            IsActive = true,
                            Name = "Free Bacon, Egg, and Rice Meal (B1) or Sausage, Egg, and Rice Meal (B2)",
                            PointsCost = 160
                        },
                        new
                        {
                            Id = 10,
                            Description = "Redeem for a free All Day Breakfast of your choice plus a mediano hot/iced americano",
                            IsActive = true,
                            Name = "Free All Day Breakfast + Americano",
                            PointsCost = 200
                        });
                });

            modelBuilder.Entity("PointsLedger", b =>
                {
                    b.HasOne("Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
