// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KapetolLoyaltyApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260707101113_UpdateRewardsSeed")]
    partial class UpdateRewardsSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QRCodeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Alec Cresencio",
                            Phone = "09279179977",
                            QRCodeId = "5c0ad0f3-da3f-4885-9037-b276bb68a7c1"
                        });
                });

            modelBuilder.Entity("PointsLedger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("PointsLedger");
                });

            modelBuilder.Entity("Reward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PointsCost")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rewards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Redeem for a free pastry of your choice",
                            IsActive = true,
                            Name = "Free Pastry",
                            PointsCost = 10
                        },
                        new
                        {
                            Id = 2,
                            Description = "Redeem for a free mediano iced tea",
                            IsActive = true,
                            Name = "Free Mediano Iced Tea",
                            PointsCost = 30
                        },
                        new
                        {
                            Id = 3,
                            Description = "Redeem for a free mediano americano",
                            IsActive = true,
                            Name = "Free Mediano Americano",
                            PointsCost = 50
                        },
                        new
                        {
                            Id = 4,
                            Description = "Redeem for a free mediano coffee or frappe",
                            IsActive = true,
                            Name = "Free Mediano Coffee/Frappe",
                            PointsCost = 70
                        },
                        new
                        {
                            Id = 5,
                            Description = "Redeem for a free all-day breakfast meal",
                            IsActive = true,
                            Name = "Free All-day Breakfast Meal",
                            PointsCost = 100
                        });
                });

            modelBuilder.Entity("PointsLedger", b =>
                {
                    b.HasOne("Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
